# Generated by Django 6.0.3 on 2026-04-02 09:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название AI модели')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Версия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'AI Модель',
                'verbose_name_plural': 'AI Модели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#3498db', help_text='Например: #3498db', max_length=7, verbose_name='Цвет (hex)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название')),
                ('content', models.TextField(help_text='Минимум 10 символов', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Текст промпта')),
                ('is_default', models.BooleanField(default=False, help_text='Промпт по умолчанию (нельзя удалить)', verbose_name='Предустановленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Количество использований')),
                ('ai_models', models.ManyToManyField(blank=True, related_name='prompts', to='prompts.aimodel', verbose_name='AI Модели')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='prompts.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='prompts', to='prompts.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Промпт',
                'verbose_name_plural': 'Промпты',
                'ordering': ['-created_at'],
            },
        ),
    ]
