# Generated by Django 6.0.3 on 2026-04-04 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название коллекции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#9b59b6', max_length=7, verbose_name='Цвет (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='prompts.collection', verbose_name='Коллекция'),
        ),
        migrations.CreateModel(
            name='PromptVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=100, verbose_name='Название переменной')),
                ('value', models.TextField(verbose_name='Значение')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='prompts.prompt', verbose_name='Промпт')),
            ],
            options={
                'verbose_name': 'Переменная промпта',
                'verbose_name_plural': 'Переменные промптов',
                'ordering': ['-used_at'],
            },
        ),
    ]
